language: rust
cache: cargo
rust:
  - nightly
  - beta
  - stable
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
script:
  - cargo test --verbose
  - cargo build --release --verbose